version: '3.3'
services:
  db:
    image: mysql:8.0  # Updated MySQL to version 8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'Inventory'  # Database name for your Spring Boot app
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'new_password'
      MYSQL_ROOT_PASSWORD: 'new_password'
    ports:
      - '3306:3306'  # Expose MySQL port
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql  # Persist MySQL data
  
  app:
    image: sanelevilakazi/stores-inventory  # Your Spring Boot app's Docker image
    depends_on:
      - db
    ports:
      - '8080:8080'  # Map the app port (Spring Boot usually runs on 8080)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Inventory  # Spring Boot connects to MySQL
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: new_password
    restart: always

volumes:
  my-db:
